### ISSUE TITLE
Invalid graphics state In call: replayPlot(x)

### ISSUE THREAD

**Issue by slfan2013** [opencpu/opencpu#200] opened 2016-08-24 03:02 UTC
If I open this url:http://128.120.143.234:1234/ocpu/tmp/x01d165fef2/graphics/last/png
then I can see the graph.

But if the result is http://128.120.143.234:1234/ocpu/tmp/x01d165fef2/graphics/last/png?width=100&height=100, then it gives the error.

Because by default, it has the width and height. So the rplot does not work.

**Comment by jeroenooms** [comment] 2016-08-24 09:06
I cannot reproduce this. If you use any of the apps with graphics such as [nabel](https://opencpu.ocpu.io/nabel/www/) you can resize the plot and link the 'png' link and it still works.

One reason you might get that error is if you upgrade R while the server is running? Try rebooting and see if the problem disappears.

**Comment by vinaybabug** [comment] 2016-10-11 20:07
Hi, 

I am also have the same problem. Not sure what details I should give but basically problem is same as described in this thread 

https://groups.google.com/forum/#!topic/opencpu/5aZwd4mM16Y

Please let me know if you found a fix.

Thank you!

**Comment by jeroenooms** [comment] 2016-10-12 12:18
This usually happens if you upgrade R without restarting. You should be able to fix this by restarting your server.

**Comment by vinaybabug** [comment] 2016-10-13 19:43
I tried restarting the server and also installed latest Java JDK as talked in the previous thread, but nothing is helping. Any pointers on how to go about fixing it.

**Comment by revosys** [comment] 2017-05-14 12:51
I m facing same problem... any solution...

**Comment by jeroen** [comment] 2017-05-14 12:55
This should have been fixed. Which version of opencpu do you tun?

**Comment by revosys** [comment] 2017-05-15 05:22
this is the script i m using... http://cdn.opencpu.org/opencpu-0.4.js

**Comment by vinaybabug** [comment] 2017-05-15 05:46
Hi revosys,

I had similar problem, to trouble shoot

1. Make sure you did not turn off the graphics in your R function that is generating the plot
2. Make sure when the R function is called from opencpu web client graph files are generated in /tmp/<your session id>/
3. Make sure your client side page can handle and show any graphics image properly.

Also, I read in other posts about opencpu version and R version compatibility. So double checking that will also be a good idea..

**Comment by revosys** [comment] 2017-05-15 05:54
this is mY CODE....

                        $("#plotdiv").rplot("plot.igraph", {
                            x: graphSession
                        },function(output){
                          console.log(output)
                        })

And Graph = graphSession is generated from

            ocpu.call("graph_from_adjacency_matrix", {adjmatrix: graph, mode:'directed', weighted:true}, function(session){

                    graphSession = session;
....

I tried http://cdn.opencpu.org/opencpu-0.5.js also.... But same result....

**Comment by vinaybabug** [comment] 2017-05-15 06:01
did you check 1 & 2 points? and also see if you can just display static image from server side to client div.

**Comment by revosys** [comment] 2017-05-15 06:02
Thanx for your reply... Please guide how to turn on the graphics in R function - plot.igraph
which variable is to be turn ON http://public.opencpu.org/ocpu/library/igraph/R/plot.igraph/print

**Comment by vinaybabug** [comment] 2017-05-15 07:42
try removing invisible(NULL) at the end of the function.

**Comment by revosys** [comment] 2017-05-15 09:24
how can i remove something from function it is hosted on public.opencpu.org...
Mycode is this

 $("#plotdiv").rplot("plot.igraph", {
                        x: graphSession
                    },function(output){
                      console.log(output)
                    })

**Comment by jeroen** [comment] 2017-05-15 11:44
@revosys the problem with http://public.opencpu.org/ocpu/tmp/x05b67ae9cd/graphics/last/png?width=800&height=100 is that 100px is too small for R to render. It works if you increase it to say 200.

http://public.opencpu.org/ocpu/tmp/x05b67ae9cd/graphics/last/png?width=800&height=200

**Comment by jeroen** [comment] 2017-05-15 12:22
Summarizing the above: some possible causes `invalid graphics state` error:

 - The plot parameters are invalid, e.g. width or height is too small for the figure
 - The R function or script your are calling is opening/closing new graphics devices. You should not do this, just print your plots and let OpenCPU record graphics
 - You upgraded R and try to render an old plot that was generated with a previous version of R.

If neither of this is the case, open a new issue with details on how your encountered this error.

**Closed by jeroen** 2017-05-15 12:22 UTC

**Comment by revosys** [comment] 2017-05-15 12:35
Thanks Jeroen for your quick reply...,

I didn't provide any width or height This url (http://public.opencpu.org/ocpu/tmp/x05b67ae9cd/graphics/last/png?width=800&height=100) is automatically fetching width height... Please guide how can control it... i didn't find any parameter for width and height in function http://public.opencpu.org/ocpu/library/igraph/R/plot.igraph/print

**Comment by jeroen** [comment] 2017-05-15 12:49
The `width` and `height` are opencpu parameters to control the graphics device. They are not related to igraph. How did you obtain that url then?

**Comment by bowofolaf** [comment] 2017-05-15 14:59
@jeroen that url is a return from the open cpu js library http://cdn.opencpu.org/opencpu-0.4.js
