### ISSUE TITLE
Error calling GetCoordLocs: R call did not return within 900 seconds. Terminating process

### ISSUE THREAD

**Issue by cbarbu** [opencpu/opencpu#131] opened 2015-01-21 10:48 UTC
This displays within 1 s of pushing the button calling this function. It was before "90 seconds" in the message but I changed the .opencpu.conf just to make sure everything is ok. I'm using opencpu 1.4.4 under:
R version 3.1.2 (2014-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)

It happens randomly: two successive calls with exactly the same arguments can succeed or not, in an unpredictible order. Nevertheless, it seems to be linked with the fact that two ocpu.rpc calls are performed at the same time: if I put a break point at the second and wait manually for the first one to finish before going on I don't get the error message.

**Comment by jeroenooms** [comment] 2015-01-21 15:32
Someone else has complained about this too. It seems to be a problem with a recent version of R. I'll try to look into it asap.

The workaround is indeed to have a little pause between doing the rpc request, and the subsequent request that (re)uses the resource.

**Comment by cbarbu** [comment] 2015-01-21 18:04
Thanks Jeroen, I used this type of workaround. A fix would be welcome
though.

2015-01-21 16:32 GMT+01:00 Jeroen Ooms <notifications@github.com>:

> Someone else has complained about this too. It seems to be a problem with
> a recent version of R. I'll try to look into it asap.
>
> The workaround is indeed to have a little pause between doing the rpc
> request, and the subsequent request that (re)uses the resource.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jeroenooms/opencpu/issues/131#issuecomment-70858007>.
>



-- 
___________________
Corentin M. Barbu-Covantes
(484) 843-1580
http://scholar.google.com/citations?hl=en&user=sxDMRdQAAAAJ
"For what does it profit a man to gain the whole world, and forfeit his
soul?" Mark 8:36

**Comment by micwalk** [comment] 2016-02-01 18:02
I ran into this issue myself running Ubuntu. This seems to be caused by a race condition in the parallel library where forking a process that completes very quickly can occasionally immediately return NULL from mccollect with wait=FALSE and a timeout.  In my case this occurred most frequently when retrieving the results from a function call that had very little data. My workaround was to add a manual timer around the mccollect call in eval_fork.R and if it returns NULL without exhausting the actual timeout period then it sleeps for 0.05 seconds and retries the mccollect call. For my usage this completely eliminated the problem. I haven't had the time to test different parameters, but I suspect that an even shorter sleep period would be sufficient.

**Comment by jeroenooms** [comment] 2016-02-01 19:38
@micwalk I have once seen this but was never able to reproduce it. I thought it was fixed by Simon, but I guess it isn't. Do you have something I can reproduce?

**Comment by micwalk** [comment] 2016-02-01 23:42
Interesting, I first encountered the problem as described by cbarbu when running opencpu inside of a docker container. When trying to create a reproducible example using an amazon ec2 instance using the same code I get the the message "R call failed: process died." as in the issue you referenced.

Regardless, here is a snippet of code used to re-create the parallel library bug:
`library(parallel)

innerTest <- function(n=100) {
    t1 <- Sys.time()
    p <- mcparallel(sqrt(n)) 
    res <- mccollect(p, wait=FALSE, timeout=2) 
    t2 <- Sys.time()
    res2 <- mccollect(p) 
    t3 <- Sys.time()
    list(colTime = t2-t1, col2Time = t3-t2, totalTime = t3-t1, r1 = res, r2=res2)
}


outerTest <- function(t=100) {
    for (n in 1:t) { 
        t3 <- innerTest(n)
        if(is.null(t3$r1)) {
            cat(n, " NULL!\n", str(t3), "\n")
        }
    }
}
`

**Comment by cbarbu** [comment] 2016-02-02 16:48
I also implemented a workaround (basically I use the callback system to
chain the calls in R, never calling two things at the same time). But would
be very interested by a fix.

Corentin

2016-02-02 0:42 GMT+01:00 Michael Walker <notifications@github.com>:

> Interesting, I first encountered the problem as described by cbarbu when
> running opencpu inside of a docker container. When trying to create a
> reproducible example using an amazon ec2 instance using the same code I get
> the the message "R call failed: process died." as in the issue you
> referenced.
>
> Regardless, here is a snippet of code used to re-create the parallel
> library bug:
> `library(parallel)
>
> innerTest <- function(n=100) {
> t1 <- Sys.time()
> p <- mcparallel(sqrt(n))
> res <- mccollect(p, wait=FALSE, timeout=2)
> t2 <- Sys.time()
> res2 <- mccollect(p)
> t3 <- Sys.time()
> list(colTime = t2-t1, col2Time = t3-t2, totalTime = t3-t1, r1 = res,
> r2=res2)
> }
>
> outerTest <- function(t=100) {
> for (n in 1:t) {
> t3 <- innerTest(n)
> if(is.null(t3$r1)) {
> cat(n, " NULL!\n", str(t3), "\n")
> }
> }
> }
> `
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jeroenooms/opencpu/issues/131#issuecomment-178259463>.
>



-- 
___________________
Corentin M. Barbu-Covantes
(484) 843-1580
http://scholar.google.com/citations?hl=en&user=sxDMRdQAAAAJ
"For what does it profit a man to gain the whole world, and forfeit his
soul?" Mark 8:36

**Comment by micwalk** [comment] 2016-02-02 16:56
The difference in errors was because RAppArmor was not running within the docker container. When applying the same fix of re-trying the mccollect call to the RAppArmor code the issue is mostly resolved on my server. I say mostly because while I no longer have any occurrences of the "Process Died" error, I also do not have 500 lines of output, which seems to indicate occasionally the http request dies without returning any information. However this was was present yesterday as well - my test output had both several process died errors as well as some missing lines of output. Strangely when running under docker / without AppArmor I never have missing lines of output, even when there are timeout errors.

My fix in both RAppArmor/eval.secure.R and opencpu/eval_fork.R is essentially this, starting from https://github.com/jeroenooms/RAppArmor/blob/master/R/eval.secure.R#L150
```R
#collect result
starttime <- Sys.time();
myresult <- mccollect(myfork, wait=FALSE, timeout=timeout);
enddtime <- Sys.time();
totaltime <- as.numeric(enddtime - starttime, units="secs")

#New code here:
#try to avoid bug/race condition where mccollect returns null without waiting full timeout.
if(is.null(myresult) && (totaltime+1) < timeout) {
    Sys.sleep(.05)
    myresult <- parallel::mccollect(myfork, wait=FALSE, timeout=timeout-(totaltime+1));
}
```

**Comment by jeroen** [comment] 2017-05-15 12:52
Cleaning up old issues. Please open a new issue if this problem still exists in OpenCPU 2.0.

**Closed by jeroen** 2017-05-15 12:52 UTC
