### ISSUE TITLE
load failed for rJava packages

### ISSUE THREAD

**Issue by hs3180** [opencpu/opencpu#85] opened 2014-03-11 09:23 UTC
for example, "/ocpu/cran/xlsxjars/R"

seems caused by .jpackage

I can't reproduce this problem when using debug mode.

**Comment by Powernap** [comment] 2015-02-25 11:27
Stumbled over this issue too. I need `rJava` because it is a dependency of the `RWeka` package, which accomplishes some tricky data mining stuff. Unfortunately there is no non-java alternative. Everything works fine in the single-user server (after I fixed some [issues with rJava and RStudio](https://powernap.github.io/blog/2015/02/20/run-rjava-with-rstudio-under-osx-10-dot-10/)). The cloud server yields the following error:

    .onLoad failed in loadNamespace() for 'rJava', details:
     call: dyn.load(file, DLLpath = DLLpath, ...)
     error: unable to load shared object '/usr/local/lib/R/site-library/rJava/libs/rJava.so':
     libjvm.so: cannot open shared object file: No such file or directory

Loading `RWeka` and `rJava` in the R session of the cloud server machine works just fine.

I assume this is related to the [LD_LIBRARY_PATH](https://stackoverflow.com/questions/12872699/error-unable-to-load-installed-packages-just-now), which is not properly set for the `OpenCPU` session, but I could not figure out how to properly pass it!

**Comment by firefaith** [comment] 2015-03-31 16:03
hit the same problem.
Loading `Rwordseg` and `rJava` in the R session works fine.
But in the server opencpu ,yeilds error: package 'rJava' could not be loaded

**Comment by jeroenooms** [comment] 2015-03-31 18:17
The underlying problem is that the cloud server forks the process a couple of times, but the JVM cannot be forked. This is one of the (many) reasons why Java is such a pain in R; other foreign language environments such as C++ or V8 (JavaScript) do support forking which makes it easy to implement parallelism.

I've been thinking about an option to disable forking, but that would also compromise reliability and security of the system, so that's not really an optimal solution.

**Comment by alliquot** [comment] 2015-09-29 07:48
Hello,
Is there any chance to find a workaround for this issue?

I'm using Java as ReporteRs package requires it. Unfortunately, there is no similar package for generating such professional looking documents.ReporteRs is my workhorse and I have nothing to replace it...

**Comment by jeroenooms** [comment] 2015-09-29 10:33
Currently the best workaround is making sure rJava does not get loaded until the actual function call (when it is needed). You can do this by by not importing rJava or ReporteR in your NAMESPACE, but instead calling `ReporteR::somefun` in your code. Thereby `rJava` only gets loaded after the fork, and you should be good.

**Comment by alliquot** [comment] 2015-09-29 11:51
Thank you very much, Jeroen!

I did what you suggested:
doc <- ReporteRs::docx();
doc <- ReporteRs::addParagraph(doc, "A paragraph");
ft <- ReporteRs::FlexTable(data);
doc <- ReporteRs::addFlexTable(doc, ft);
ReporteRs::writeDoc(doc, "test.docx");

Errors related to Java disappeared, but a new error has been thrown: "function returned without calling respond". Does it make any clues what could go wrong?

**Comment by jeroenooms** [comment] 2015-09-29 11:57
Mmm that usually means something pretty bad went wrong, for example the server ran out of memory. Did you restart apache? Is there anything odd in apache error log or kern.log?

**Comment by alliquot** [comment] 2015-09-29 12:10
Unfortunately, no suspicious entries.

In Apache log - only the one about disabled AppArmor (and I'm getting it constantly, even when the server runs well)
----
Checking Apparmor Status...
 AppArmor status lookup failed. Error code: ECANCELED
AppArmor is available on the system but has been disabled at boot.
AppArmor not available. Running OpenCPU without security profile but with rlimit
OpenCPU cloud server ready.
OpenCPU cloud server ready.
OpenCPU cloud server ready.
OpenCPU cloud server ready.
OpenCPU cloud server ready.
----
Nothing suspicious in kern.log as well.

When I commented out these references to ReporteRs, everything started working correctly.

**Comment by jeroenooms** [comment] 2015-09-29 12:11
Nothing in `/var/log/kern.log` ?

**Comment by alliquot** [comment] 2015-09-29 12:29
Completely nothing :(

I missed recently error in Apache error log (occurs after refreshing/loading page): [Tue Sep 29 13:26:38.264622 2015] [:error] [pid 7248] [client 192.168.1.12:62526] rApache Notice!, referer: http://192.168.1.13/ocpu/libraryTest1/www/index.html
OpenCPU cloud server ready.

**Comment by jeroenooms** [comment] 2015-09-29 12:32
That warning is harmless. Ugh I don't know, Java really messes with the webserve. Does the same happen for other Java packages or just ReporteR?

**Comment by alliquot** [comment] 2015-09-29 13:06
Yes, this happens with other 'java-based' packages as well. I've tried xlsx (both library(xlsx) and xlsx::fn).

So it seems this issue is common.
Well, anyway thank you for your efforts and time!

**Comment by alliquot** [comment] 2015-10-02 13:44
BTW, I've tried to do it other way - call Rscript with a script containing all Java-based function references. Without success but at least got some clues:

    [1] "Error occurred during initialization of VM"    
    [2] "Could not allocate metaspace: 1073741824 bytes"
    attr(,"status")

Perhaps you'll find this useful for something :)

**Comment by jeroenooms** [comment] 2015-10-02 13:47
Oh wow that is a lot of memory it needs. Can you try increasing `rlimit.as` in `/etc/opencpu.d/opencpu.conf` ?

**Comment by alliquot** [comment] 2015-10-03 00:03
It works :)

Steps to reproduce it:
1. mcedit /etc/opencpu/server.conf, change rlimit.as: 2e9 -> 3e9, restart the server
1. install on the server: Java (then r cmd javareconf), rJava, ReporteRs
2. create a simple R script containing the following content:

_docCreate.r_

    library(ReporteRs)
    args <- commandArgs(trailingOnly = TRUE)
    print(args[1])
    doc <- docx();
    doc <- addParagraph(doc, "Some story...");
    ft <- FlexTable(data.frame(a=1:10, b=LETTERS[1:10]));
    doc <- addFlexTable(doc, ft);
    writeDoc(doc, paste0(args[1], "/TestReport.docx"));

2. save it into inst/www

3. in R code refer to it:

    path <- getwd()
    print(file.path(path, "TestReport.docx"))
    system.time(system(paste("Rscript /usr/local/lib/R/site-library/MyPackage/www/docCreate.r", path), wait = TRUE, intern = T)) # intern to get the output

4. build src package, install as usual

A new item should appear:
/ocpu/tmp/x0acd994395/R/.val
/ocpu/tmp/x0acd994395/stdout
/ocpu/tmp/x0acd994395/warnings
/ocpu/tmp/x0acd994395/source
/ocpu/tmp/x0acd994395/console
/ocpu/tmp/x0acd994395/info
/ocpu/tmp/x0acd994395/files/DESCRIPTION
*/ocpu/tmp/x0acd994395/files/TestReport.docx*

But the process is terrrrrible slooow:
http://192.168.1.13/ocpu/tmp/x0acd994395/console/text

    > MakeReportDocument()
    [1] "/tmp/ocpu-temp/ocpu_session_2a7f4a196232"
    [1] "/tmp/ocpu-temp/ocpu_session_2a7f4a196232/TestReport.docx"
       user  system elapsed 
     12.460   0.716  13.473 

almost 14 seconds...
So yes, it does work, but is not very useful.

**Comment by jeroen** [comment] 2017-05-15 12:54
The problem with `java` should be resolved in OpenCPU 2.0. I don't use Java a lot myself so I would love to hear if this now works. Please open a new issue if this problem still exists in OpenCPU 2.0.

**Closed by jeroen** 2017-05-15 12:54 UTC
